CREATE TABLE t_sample (
	id UUID NOT NULL DEFAULT uuid_generate_v4(),
	name VARCHAR(128) NOT NULL UNIQUE,
	timestamp_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	timestamp_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	timestamp_last_accessed TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);